Add Season 12 features to training set

In [7]:
# baker -> place
s12 = {
'Giuseppe': 1,
'Chigs': 2,
'Crystelle': 2,
'Jürgen': 3,
'Lizzie': 4,
'George': 5,
'Amanda': 6,
'Freya': 7,
'Maggie': 8,
'Rochica': 9,
'Jairzinho': 10,
'Tom': 11,
}

In [8]:
import pandas as pd
import numpy as np
from scipy import interp
import scipy.stats
from sklearn.preprocessing import QuantileTransformer
from datetime import datetime

In [9]:
def timestamp(): return datetime.today().strftime('%Y%m%d')

In [10]:
def quantile_scale(df,feats):
    qua = df
    scaler = QuantileTransformer(
        n_quantiles=10,
        random_state=42,
        ignore_implicit_zeros=True, #sparse matrix
    )
    # fit the scaler
    scaler.fit(qua[feats])
    # transform values
    qua[feats] = scaler.transform(qua[feats])
    return qua

In [11]:
df = pd.read_csv('../S12/deepbake_features_s12_e10.tsv',sep='\t')
df['place'] = df['baker'].map(s12)

In [12]:
tech = pd.read_csv("../../RESULTS/deepbake_features.20210926.tsv",sep='\t')
df2 = pd.concat([tech[df.columns],df])
df2.to_csv('../../RESULTS/deepbake_features.20221002.tsv',sep='\t',index=False)

In [17]:
def scale_gbbo(episode):
    df = pd.read_csv(f'../S12/deepbake_features_s12_e{episode}.tsv',sep='\t')
    feats = ['tech_mean','tech','mean_star','star','mean_good','good','mean_bad','bad']
    df2 = df.loc[df['episode']==episode].copy()
    df2 = quantile_scale(df2,feats)
    return df2

In [18]:
scale_gbbo(10)

/usr/local/lib/python3.9/site-packages/sklearn/preprocessing/_data.py:2263: UserWarning: 'ignore_implicit_zeros' takes effect only with sparse matrix. This parameter has no effect.
  warnings.warn("'ignore_implicit_zeros' takes effect only with"

,season,baker,episode,tech_mean,tech,mean_star,star,mean_good,good,mean_bad,bad
9,12,Amanda,10,0.717949,0.0,0.000000,0.0,0.000000,0.0,1.000000,0.0
19,12,Chigs,10,0.814815,0.9,0.833333,0.0,0.777778,0.0,0.000000,0.0
29,12,Crystelle,10,1.000000,0.8,0.833333,0.0,0.777778,0.0,0.277778,0.0
39,12,Freya,10,0.108696,0.0,0.000000,0.0,0.583333,0.0,0.666667,0.0
49,12,George,10,0.890000,0.0,0.000000,0.0,0.388889,0.0,1.000000,0.0
59,12,Giuseppe,10,0.600000,1.0,0.833333,0.0,1.000000,0.0,0.277778,0.0
69,12,Jürgen,10,0.289855,0.0,1.000000,0.0,0.909091,0.0,0.277778,0.0
79,12,Lizzie,10,0.500000,0.0,0.000000,0.0,0.388889,0.0,0.666667,0.0
89,12,Maggie,10,0.206349,0.0,0.000000,0.0,0.388889,0.0,0.800000,0.0
99,12,Rochica,10,0.392157,0.0,0.000000,0.0,0.000000,0.0,0.277778,0.0
109,12,Tom,10,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.277778,0.0