Add Season 11 features to training set

In [1]:
# baker -> place
s11 = {
    'Peter' : 1,
    'Dave' : 2,
    'Laura': 2,
    'Hermine' : 3,
    'Marc' : 4,
    'Lottie' : 5,
    'Mark' : 6,
    'Linda' : 7,
    'Sura' : 8,
    'Rowan' : 9,
    'Mak' : 10,
    'Loriea' : 11
}

In [2]:
import pandas as pd
import numpy as np
from scipy import interp
import scipy.stats
from sklearn.preprocessing import QuantileTransformer
from datetime import datetime

In [3]:
def timestamp(): return datetime.today().strftime('%Y%m%d')

In [4]:
def quantile_scale(df,feats):
    qua = df
    scaler = QuantileTransformer(
        n_quantiles=10,
        random_state=42,
        ignore_implicit_zeros=True, #sparse matrix
    )
    # fit the scaler
    scaler.fit(qua[feats])
    # transform values
    qua[feats] = scaler.transform(qua[feats])
    return qua

In [5]:
df = pd.read_csv('../S11/deepbake_features_s11_e10.tsv',sep='\t')
df['place'] = df['baker'].map(s11)

In [6]:
tech = pd.read_csv("../../RESULTS/deepbake_features.20201016.tsv",sep='\t')
df2 = pd.concat([tech[df.columns],df])
df2.to_csv('../../RESULTS/deepbake_features.20210926.tsv',sep='\t',index=False)

In [7]:
def scale_gbbo(episode):
    df = pd.read_csv(f'../S11/deepbake_features_s11_e{episode}.tsv',sep='\t')
    feats = ['tech_mean','tech','mean_star','star','mean_good','good','mean_bad','bad']
    df2 = df.loc[df['episode']==episode].copy()
    df2 = quantile_scale(df2,feats)
    return df2

In [8]:
scale_gbbo(10)

/usr/local/lib/python3.9/site-packages/sklearn/preprocessing/_data.py:2263: UserWarning: 'ignore_implicit_zeros' takes effect only with sparse matrix. This parameter has no effect.
  warnings.warn("'ignore_implicit_zeros' takes effect only with"

,season,baker,episode,place,tech_mean,tech,mean_star,star,mean_good,good,mean_bad,bad
9,11,Dave,10,0,0.194872,0.818182,0.666667,0.0,1.000000,0.0,0.000000,0.0
19,11,Hermine,10,0,0.727273,0.000000,1.000000,0.0,1.000000,0.0,0.611111,0.0
29,11,Laura,10,0,1.000000,1.000000,0.666667,0.0,0.555556,0.0,1.000000,0.0
39,11,Linda,10,0,0.532407,0.000000,0.000000,0.0,0.000000,0.0,1.000000,0.0
49,11,Loriea,10,1,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0
59,11,Lottie,10,0,0.795556,0.000000,0.666667,0.0,0.363636,0.0,0.000000,0.0
69,11,Mak,10,2,0.043478,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0
79,11,Marc,10,0,1.000000,0.000000,0.666667,0.0,1.000000,0.0,1.000000,0.0
89,11,Mark,10,0,0.363636,0.000000,0.666667,0.0,0.555556,0.0,0.611111,0.0
99,11,Peter,10,0,0.646259,0.909091,1.000000,0.0,0.727273,0.0,0.611111,0.0
109,11,Rowan,10,3,0.449074,0.000000,0.000000,0.0,0.000000,0.0,0.611111,0.0
119,11,Sura,10,4,0.307692,0.000000,0.000000,0.0,0.555556,0.0,0.000000,0.0